apiVersion: v1
kind: Pod
metadata:
  name: deep-gtex
spec:
  containers:
  - name: deep-gtex-container
    image: docker.io/cbmckni/deep-gtex
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
    - name: data
      hostPath:
        path: /deep-gtex/data
