apiVersion: v1
kind: Pod
metadata:
  name: gene-oracle
spec:
  containers:
  - name: gene-oracle-container
    image: docker.io/cbmckni/gene-oracle
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: 1
